#!/usr/bin/env python3
"""Create an original synthetic two-sheet PDF for local workspace demonstrations.

Usage: python3 scripts/create-drawing-workspace-demo.py NEW_OUTPUT.pdf
No dependencies, external sources, private drawings, or authoritative quantities.
The destination must not exist. Generated bytes are runtime demonstration data,
not an admitted production drawing or governed Foundation test fixture.
"""

import argparse
from pathlib import Path


def label(x, y, size, value):
    escaped = value.replace("\\", "\\\\").replace("(", "\\(").replace(")", "\\)")
    return "BT /F1 {} Tf {} {} Td ({}) Tj ET\n".format(size, x, y, escaped)


def page_content(width, height, sheet, title):
    content = ["0.15 0.20 0.20 RG 3 w\n", "48 48 {} {} re S\n".format(width-96, height-96)]
    content.append(label(78, height-108, 38, "HELEOS / DRAWING WORKSPACE"))
    content.append(label(78, height-154, 22, "SYNTHETIC DEMONSTRATION - NOT FOR CONSTRUCTION"))
    content.append(label(78, height-224, 32, title))
    content.append(label(78, height-267, 20, "Original local fixture. No project data or external source content."))
    content.extend([
        "0.85 0.88 0.86 RG 2 w\n",
        "120 350 {} {} re S\n".format(width-240, height-720),
        "0.12 0.35 0.34 RG 5 w\n",
        "260 550 {} 80 re S\n".format(width-600),
        "{} 590 m {} 850 l S\n".format(width//2, width//2),
        "{} 820 100 100 re S\n".format(width//2-50),
        "310 500 100 100 re S\n",
        "{} 500 100 100 re S\n".format(width-470),
    ])
    content.append(label(268, 668, 20, "Illustrative airside symbols - no calibrated scale"))
    content.append(label(78, 230, 22, "SHEET " + sheet))
    content.append(label(78, 180, 20, "Use this file to check import, page selection, rotation and original-PDF preview."))
    content.append(label(78, 138, 20, "Geometry is synthetic. Measurements and quantities have not been accepted."))
    content.append(label(78, 88, 16, "Paper: {} x {} inches | Display metadata only".format(width//72, height//72)))
    return "".join(content).encode("ascii")


def build_pdf():
    page_one = page_content(2592, 1728, "M-001", "AIR DISTRIBUTION / DEMONSTRATION PLAN")
    page_two = page_content(1728, 1296, "M-002", "AIR DISTRIBUTION / ROTATED SHEET")
    objects = [
        b"<< /Type /Catalog /Pages 2 0 R >>",
        b"<< /Type /Pages /Kids [3 0 R 4 0 R] /Count 2 >>",
        b"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 2592 1728] /Resources << /Font << /F1 5 0 R >> >> /Contents 6 0 R >>",
        b"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 1728 1296] /Rotate 90 /Resources << /Font << /F1 5 0 R >> >> /Contents 7 0 R >>",
        b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",
        b"<< /Length " + str(len(page_one)).encode("ascii") + b" >>\nstream\n" + page_one + b"endstream",
        b"<< /Length " + str(len(page_two)).encode("ascii") + b" >>\nstream\n" + page_two + b"endstream",
    ]
    result = bytearray(b"%PDF-1.7\n%\x80\x81\x82\x83\n")
    offsets = []
    for number, obj in enumerate(objects, 1):
        offsets.append(len(result))
        result.extend(str(number).encode("ascii") + b" 0 obj\n" + obj + b"\nendobj\n")
    xref = len(result)
    result.extend("xref\n0 {}\n0000000000 65535 f \n".format(len(objects)+1).encode("ascii"))
    for offset in offsets:
        result.extend("{:010} 00000 n \n".format(offset).encode("ascii"))
    result.extend("trailer\n<< /Size {} /Root 1 0 R >>\nstartxref\n{}\n%%EOF\n".format(len(objects)+1, xref).encode("ascii"))
    return bytes(result)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("output", type=Path)
    args = parser.parse_args()
    with args.output.open("xb") as destination:
        destination.write(build_pdf())
    print("Created synthetic two-sheet drawing: {}".format(args.output))


if __name__ == "__main__":
    main()
